# Nixpacks Configuration for Discord Ticket Bot

[variables]
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
dependsOn = []

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"] 
cmds = []

[start]
cmd = "npm start"
